# Generated by Django 5.1.4 on 2024-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seiketsu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContopCounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("jumlah_contop", models.PositiveIntegerField()),
                ("gambar_terakhir", models.ImageField(upload_to="contop_frames/")),
            ],
        ),
        migrations.DeleteModel(
            name="check",
        ),
    ]
